### ISSUE TITLE
Why the use of IO in the core?

### ISSUE THREAD

**Issue by eyeinsky** [re-xyr/cleff#11]
This is probably a effect-systems novice question, but why use IO at the core of things that may otherwise don't require IO? E.g reader/writer/state don't require IO by themselves. Is this mostly to solve a performance issue where ghc can't optimize things well enough?

**Comment by re-xyr** [comment]
Using `IORef`s for writer and state has the following upsides:

- They tend to have stable (and pretty good) performance, as opposed to transformer-style writer/state whose performance can vary greatly depending on optimization, boxedness etc.
- Also, transformer-style writer leaks memory from what I hear. This won't happen for IORef-based versions.
- They interact well with concurrency and exceptions (you will not lose state when exception is thrown).

Many other libraries are polymorphic in the base monad (e.g. polysemy), what that costs is 1) performance, since GHC cannot optimize for any particular monad, and 2) hard or downright impossible to implement certain operations (see how `weave` - an integral part of higher-order effects in polysemy - is implemented: https://reasonablypolymorphic.com/blog/freer-higher-order-effects/). `IO` allows us to implement many nice operations easily and is strong enough (support for concurrency, exceptions, mutable states, etc) for most applications.

**Comment by eyeinsky** [comment]
Right, regarding polysemy, the insides of it are really complicated -- just recently looked at it and both Weave and Tactics are 1) beyond what I can comprehend atm :), and 2) the are in the center of every other effect (all the prominent monads are implemented using at least Tactics).

But what I was getting at was that it looks like the way to do a performant monad stack is just to slap *the most powerful effect* at the center and interpret everything according to that. It does perform but isn't there anything lesser that could be used that the compiler could be persuaded to do to compile away the intermediate representations? I get that IO is hidden away from the API, but it still feels like stop-gap solution to get the extensible effects API while postponing a pure implementation.

**Comment by re-xyr** [comment]
I'd say it's a stop-gap solution from a *polymorphic* implementation (polymorphic in the base monad). A polymorphic impelementation that is also flexible *and* performant enough is still not quite possible at this point. When we use `IO` we're limited to what compiler gives us, and that does not look quite "future proof" indeed. So, `cleff` may only be of some practical value in the short- to mid-term, instead of being a silver bullet.

**Comment by re-xyr** [comment]
Closing for now - welcome to reopen if you have any further questions @eyeinsky.
