### ISSUE TITLE
Distribution of `cleff-plugin`

### ISSUE THREAD

**Issue by re-xyr** [re-xyr/cleff#14]
There are three choices as I see:

- Maintain one package that supports `cleff`, `effectful` and `polysemy` with conditional compilation
  - conditional compilation is not generally a good practice (especially not for this kind of usage)
  - maintanence burden on me
- Maintain a "core" package that supplies functionalities to separate plugins for separate libraries
  - a bit of clutter, since we need to have 4 more packages
  - the core package is responsible for all compatibility, so maintanence burden still on me
- Only maintain a `cleff` version, let other packages fork
  - Unnecessary out-of-sync and code duplication possible

@arybczak what do you think?

**Comment by arybczak** [comment]
Yeah, it's a tough choice.

IMO (1) is the least feasible because of the maintenance burden. (2) is the best in theory, but we can go with (3) for now as it seems to be the cheapest (not collectively, but for every single person involved) and see how it goes. The code is fairly straightforward, there isn't much of it and it won't change much (if at all) in the future.

After all (3) can always be converted into (2) (with the core package moved to a GitHub organization perhaps to alleviate the maintenance burden).

**Comment by re-xyr** [comment]
Nice analysis, thanks! I think I'll use (3) for now.
