### ISSUE TITLE
Effects from Mem are never dropped

### ISSUE THREAD

**Issue by arybczak** [re-xyr/cleff#7]
I was pondering the possibility of adapting the model of having `Env` only store references to representations of effects in `effectful` and realized that getting rid of effects that are no longer needed becomes somewhat problematic because of the indirection.

In fact, `cleff` currently doesn't do that at all, so an expression `runEff . forever . runReader () $ pure ()` eventually consumes all available memory.

**Comment by re-xyr** [comment]
I tried running the example you gave and I did not get increasing memory consumption. I'm pretty sure it won't; it should not accumulate a large `Env` but instead multiple small `Env`s that are thrown away each time.

As for the problem of memory leak, I have thought about it too. My conclusion was that the new approach do not really create new chances for leaking. For recursive scoped effects, leak is minimal because `runHere` does not really create a new cell in the `Env` - it changes an existing cell. As for the `interpret` function family that does create new cells, normal usage won't use them inside recursive application code. Even if someone attempts to do that, there isn't really much we can do - things like a long chain of recursive `interpose` indeed creates many cells, but it would really be the same situation before the change as the new handler will always hold a reference to the old one so even in older versions of `cleff` they wouldn't be GCed either.

With that said, my conclusion may be wrong, it is just that I've yet to find a counterexample. I'd be happy to investigate if you found one.

**Comment by arybczak** [comment]
Ok, so `runIOE . forever . runReader () $ pure ()` leaks memory is `ghci` or when compiled with `-O0`, but not when compiled with `-O1` :thinking:

**Comment by re-xyr** [comment]
Well, that's perhaps because `-O0` doesn't do tail call optimization.

**Comment by arybczak** [comment]
> Well, that's perhaps because -O0 doesn't do tail call optimization.

Perhaps, though neither `effectful` nor `polysemy` leak, so it's a bit weird.

> it should not accumulate a large Env but instead multiple small Envs that are thrown away each time.

You're right, that is in fact the case. I'll close the issue then.

**Comment by re-xyr** [comment]
> Perhaps, though neither effectful nor polysemy leak, so it's a bit weird.

This is weird. I'll probably still look into it.
